remote_theme: benbalter/retlab
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

gem "github-pages", group: :jekyll_plugins

title: SyncAi2Brain
description: Learn Ai
markdown: kramdown
math: katex
