remote_theme: sylhare/Type-on-Strap
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-paginate
- jekyll-seo-tag
- jekyll-feed

katex: true                                             # Enable if using math markup
mermaid: default                                        # Enable mermaid-js for diagrams, use theme: base, forest, dark, default, neutral
color_theme: auto                                       # auto, dark or light
baseurl: ""
url: "https://syncai2brain.github.io"

title: SyncAi2Brain
description: Learn Ai


